"""
Safe Script Runner
==================
Executes the modified training script in a sandboxed subprocess.

Safety rules:
  - Script must be a real .py file on disk (not a string from LLM)
  - 60-second hard timeout
  - Captures full stdout/stderr
  - Validates that output_model.pkl was created
  - Never executes arbitrary strings
"""

from __future__ import annotations

import logging
import os
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Optional

import joblib

logger = logging.getLogger("courtroom.runner")

DEFAULT_TIMEOUT = 60  # seconds


def run_script(
    script_path: str | Path,
    working_dir: str | Path,
    timeout: int = DEFAULT_TIMEOUT,
    env_extra: Optional[dict] = None,
) -> dict:
    """
    Execute a Python training script in a subprocess.

    Args:
        script_path:  Absolute path to the .py script to execute.
        working_dir:  Working directory for the subprocess (where dataset.csv lives).
        timeout:      Max seconds to wait (default 60).
        env_extra:    Extra environment variables to pass to the subprocess.

    Returns:
        {
            "success": bool,
            "returncode": int,
            "stdout": str,
            "stderr": str,
            "output_model_path": str | None,
        }
    """
    script_path = Path(script_path).resolve()
    working_dir = Path(working_dir).resolve()

    if not script_path.exists():
        raise FileNotFoundError(f"Script not found: {script_path}")

    if not working_dir.exists():
        raise FileNotFoundError(f"Working directory not found: {working_dir}")

    # Use the same Python interpreter that's running the backend
    python_exe = sys.executable

    env = os.environ.copy()
    if env_extra:
        env.update(env_extra)

    logger.info("Running script: %s (cwd=%s, timeout=%ds)", script_path, working_dir, timeout)

    try:
        proc = subprocess.run(
            [python_exe, str(script_path)],
            cwd=str(working_dir),
            capture_output=True,
            text=True,
            timeout=timeout,
            env=env,
        )
    except subprocess.TimeoutExpired:
        logger.error("Script execution timed out after %ds: %s", timeout, script_path)
        return {
            "success": False,
            "returncode": -1,
            "stdout": "",
            "stderr": f"Script timed out after {timeout} seconds.",
            "output_model_path": None,
        }
    except Exception as exc:
        logger.error("Script execution error: %s", exc)
        return {
            "success": False,
            "returncode": -1,
            "stdout": "",
            "stderr": str(exc),
            "output_model_path": None,
        }

    # Log output
    if proc.stdout:
        for line in proc.stdout.splitlines()[-20:]:  # Last 20 lines
            logger.info("[script stdout] %s", line)
    if proc.stderr:
        for line in proc.stderr.splitlines()[-20:]:
            logger.warning("[script stderr] %s", line)

    if proc.returncode != 0:
        logger.error(
            "Script exited with code %d.\nStdout: %s\nStderr: %s",
            proc.returncode,
            proc.stdout[-500:],
            proc.stderr[-500:],
        )
        return {
            "success": False,
            "returncode": proc.returncode,
            "stdout": proc.stdout,
            "stderr": proc.stderr,
            "output_model_path": None,
        }

    # Verify output model was saved
    output_model_path = working_dir / "output_model.pkl"
    if not output_model_path.exists():
        logger.error(
            "Script ran successfully but output_model.pkl was NOT created in %s", working_dir
        )
        return {
            "success": False,
            "returncode": 0,
            "stdout": proc.stdout,
            "stderr": "output_model.pkl was not created. "
                      "Ensure the script contains: joblib.dump(model, 'output_model.pkl')",
            "output_model_path": None,
        }

    logger.info("Script completed successfully. Model saved to: %s", output_model_path)
    return {
        "success": True,
        "returncode": 0,
        "stdout": proc.stdout,
        "stderr": proc.stderr,
        "output_model_path": str(output_model_path),
    }


def load_output_model(working_dir: str | Path):
    """
    Load the output_model.pkl generated by run_script().

    Returns the model object.
    Raises RuntimeError if not found or cannot be loaded.
    """
    model_path = Path(working_dir) / "output_model.pkl"
    if not model_path.exists():
        raise RuntimeError(
            f"output_model.pkl not found in {working_dir}. "
            "The training script must save the model with: joblib.dump(model, 'output_model.pkl')"
        )

    try:
        model = joblib.load(str(model_path))
        logger.info("Loaded output model: %s", type(model).__name__)
        return model
    except Exception as exc:
        raise RuntimeError(f"Failed to load output_model.pkl: {exc}") from exc


def save_script_to_temp(source: str, suffix: str = "_mitigated.py") -> Path:
    """
    Write script source to a named temp file and return the path.
    The caller is responsible for deleting it.
    """
    fd, path = tempfile.mkstemp(suffix=suffix, prefix="cephus_")
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        f.write(source)
    return Path(path)
